<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            line-height: 1.5;
            margin: 0;
            padding: 0;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #1B6B3A;
            padding-bottom: 10px;
        }
        .school-name {
            font-size: 20px;
            font-weight: bold;
            color: #1B6B3A;
            text-transform: uppercase;
        }
        .school-address {
            font-size: 12px;
            color: #666;
        }
        .report-title {
            font-size: 18px;
            margin-top: 15px;
            font-weight: bold;
            color: #333;
        }
        .report-subtitle {
            font-size: 13px;
            color: #555;
            margin-top: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 11px;
        }
        th {
            background-color: #F0F7F0;
            color: #1B6B3A;
            text-align: left;
            padding: 8px;
            border: 1px solid #ddd;
            text-transform: uppercase;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
        }
        .summary-box {
            margin-top: 20px;
            padding: 15px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        .summary-title {
            font-weight: bold;
            font-size: 14px;
            margin-bottom: 10px;
            color: #1B6B3A;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        .summary-item {
            margin-bottom: 5px;
            font-size: 12px;
            overflow: hidden;
            clear: both;
        }
        .summary-item .left {
            float: left;
        }
        .summary-item .right {
            float: right;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            font-size: 10px;
            color: #888;
            text-align: center;
            padding-top: 10px;
            border-top: 1px solid #eee;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
        .status-badge {
            padding: 2px 6px;
            border-radius: 10px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .status-pending { background-color: #FFF3CD; color: #856404; }
        .status-ready { background-color: #D4EDDA; color: #155724; }
        .status-completed { background-color: #CFE2FF; color: #084298; }
        .status-cancelled { background-color: #F8D7DA; color: #721C24; }
        
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div class="school-name">CITY COLLEGE OF SENIOR TRIAS</div>
        <div class="school-address">City of General Trias, Cavite, Philippines</div>
        <div class="report-title">{{ $title }}</div>
        <div class="report-subtitle">{{ $subtitle }}</div>
    </div>

    @yield('report_content')

    @if(isset($includeSummary) && $includeSummary)
        <div class="summary-box">
            <div class="summary-title">Summary Statistics</div>
            @yield('summary_content')
        </div>
    @endif

    <div class="footer">
        <div style="float: left;">Generated on: {{ $generated_at }}</div>
        <div style="float: right;" class="page-number"></div>
        <div style="clear: both;">Generated by: {{ $generated_by }}</div>
    </div>
</body>
</html>
